# Generated by Django 2.2.5 on 2019-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod_data',
            name='email',
            field=models.EmailField(default='hod@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hod_data',
            name='first_name',
            field=models.CharField(default='Prof. Deepak', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hod_data',
            name='last_name',
            field=models.CharField(default='Mehtre', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hod_data',
            name='mobile_no',
            field=models.BigIntegerField(default=1234567891),
            preserve_default=False,
        ),
    ]
