# Generated by Django 2.2.5 on 2019-09-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gfm_signup',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='gfm_signup',
            name='password2',
        ),
    ]
