# Generated by Django 2.2.5 on 2019-09-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfm', '0002_auto_20190929_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfm_signup',
            name='valid',
            field=models.CharField(default='pending', max_length=8),
            preserve_default=False,
        ),
    ]
