# Generated by Django 2.2.5 on 2019-09-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190930_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_req',
            name='in_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='in_req',
            name='req_accept_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
