# Generated by Django 2.2.5 on 2019-10-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20191001_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_req',
            name='request_type',
            field=models.CharField(default='IN Request', max_length=100),
        ),
    ]
