# Generated by Django 2.2.5 on 2019-10-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20191002_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_req',
            name='req_count',
            field=models.IntegerField(default=0),
        ),
    ]
