# Generated by Django 2.2.5 on 2019-10-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_in_req_req_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_req',
            name='req_date',
            field=models.DateField(default='2019-10-03'),
            preserve_default=False,
        ),
    ]
