# Generated by Django 2.2.5 on 2019-10-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_in_req_req_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in_req',
            old_name='req_count',
            new_name='in_req_count',
        ),
        migrations.AddField(
            model_name='in_req',
            name='out_req_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='in_req',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='in_req',
            name='request_type',
            field=models.CharField(max_length=100),
        ),
    ]
