# Generated by Django 3.0 on 2019-12-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20191003_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_req',
            name='branch',
            field=models.CharField(default='computer', max_length=100),
        ),
        migrations.AddField(
            model_name='in_req',
            name='req_acceped_by',
            field=models.CharField(default='hod', max_length=320),
        ),
        migrations.AddField(
            model_name='in_req',
            name='year',
            field=models.CharField(default='FE', max_length=2),
        ),
    ]
