# Generated by Django 3.0 on 2020-01-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20191226_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_signup',
            name='otp',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
