# Generated by Django 3.0 on 2020-01-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20200112_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_signup',
            name='emial_otp',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
