# Generated by Django 3.0 on 2020-01-12 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_stu_signup_emial_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stu_signup',
            old_name='emial_otp',
            new_name='email_otp',
        ),
    ]
