# Generated by Django 3.0 on 2020-01-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20200112_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_verifiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=60)),
            ],
        ),
    ]
