# Generated by Django 3.0 on 2020-01-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20200117_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_signup',
            name='icard_img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stu_signup',
            name='user_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
